# Generated by Django 4.2.3 on 2023-07-21 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_users_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Payment', 'Ожидает оплаты'), ('Preparing', 'Готовится'), ('In delivery', 'Доставляется'), ('Completed', 'Завершен')], default='Payment', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
