# Generated by Django 4.2.3 on 2023-07-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orders_delivery_address_orders_delivery_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utmcheckin',
            name='page',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адрес страницы'),
        ),
    ]
