# Generated by Django 4.2.3 on 2023-07-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_utmcheckin_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_content',
            field=models.CharField(blank=True, max_length=250, verbose_name='Идентификатор объявления'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=10, verbose_name='Тип траффика'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100, verbose_name='Источник UTM'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_term',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ключевое слово'),
        ),
    ]
