# Generated by Django 4.2.3 on 2023-07-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_utmcheckin_page_alter_utmcheckin_utm_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utmcheckin',
            name='page',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Адрес страницы'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Идентификатор объявления'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Тип траффика'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Источник UTM'),
        ),
        migrations.AlterField(
            model_name='utmcheckin',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ключевое слово'),
        ),
    ]
